version: "3"

tasks:
  clean:
    cmds:
      - rm -rf ./docs
      - rm -rf ./web
      - rm -rf ./tmp

  tidy-n-fmt:
    cmds:
      - go mod tidy
      - go fmt ./...

  npm-deps:
    cmds:
      - npm install

  bundle:
    cmds:
      - ./node_modules/.bin/esbuild index.js --bundle --outfile=./web/index.js
      - cp -R ./static ./web/

  build-webapp:
    cmds:
      - task: tidy-n-fmt
      - task: bundle
      - GOARCH=wasm GOOS=js go build -o ./web/app.wasm ./cmd/...

  build:
    cmds:
      - task: build-webapp
      - go build -o tmp/goapp-clock ./cmd/...

  run:
    cmds:
      - task: build-webapp
      - go run ./cmd/... --serve

  dev:
    cmds:
      - task: tidy-n-fmt
      - task: npm-deps
      - air

  gh-pages:
    cmds:
      - task: build-webapp
      - go run ./cmd/... --build --path goapp-clock --out docs
      - mv ./web/* ./docs/web/ && rm -r ./web
