name: github-pages

on:
  push:
    branches:
      - "main"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.21"
          cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Node Deps
        run: "npm install"
        shell: bash

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Build Static Website
        run: "task gh-pages"
        shell: bash

      - name: Commit Static Website
        run: |
          git config --global user.name 'GH Actions'
          git config --global user.email 'pthomison+gh-actions-goapp-clock@gmail.com'
          git commit -am "Doc Updates"
          git checkout docs
          git merge main
          git push
